version: "0.2"
ignorePaths: []
dictionaryDefinitions:
  - name: custom-dictionary
    path: ./.cspell/custom-dictionary.txt
    addWords: true
dictionaries:
  - custom-dictionary
words:
  - Capacites
  - endregion
  - finsihed
  - Pipeliness
  - powerbi
  - powerbicapacities
  - powerbigateways
  - powerbipipelines
  - powerbiworkspaces
  - tmdl
  - TMDL
  - treeviews
ignoreWords: []
import: []
